export type Term = { title: string; what: string; how: string; why: string; action: string };

export const GLOSSARY: Record<string, Term> = {
  suspicion: {
    title: "Label suspicion (evidence score)",
    what: "A 0–1 evidence score summarising how strongly independent witnesses disagree with the current label. It is not a probability that the label is wrong.",
    how: "Weighted mean of normalised signals: 1 − model probability of the given label (out-of-fold), 1 − neighbour agreement, centroid distance, training-dynamics difficulty and duplicate label conflict. Each weight is scaled by that witness's measured reliability on this dataset.",
    why: "Ranks where human attention is most likely to find a labelling problem.",
    action: "Review from the top. Treat high scores as 'worth a look', never as automatic relabels.",
  },
  neighbor_agreement: {
    title: "Neighbour agreement",
    what: "Similarity-weighted share of the k nearest samples (in embedding space) that carry the same label.",
    how: "k-NN over normalised embeddings (exact cosine search). Copies of the sample from its own duplicate family are excluded so they cannot vote.",
    why: "A label that none of its visual neighbours share is a classic sign of a labelling error — or of a rare case.",
    action: "Compare the sample with its neighbours side by side in the case view.",
  },
  centroid_ratio: {
    title: "Centroid distance ratio",
    what: "Where the sample sits between its own class centre and the nearest other class centre.",
    how: "d_own / (d_own + d_nearest_other) with cosine distances to class centroids computed on training data. Above 0.5 = closer to another class.",
    why: "Samples that live inside another class's region are often mislabelled or ambiguous.",
    action: "Check whether the image matches the other class better.",
  },
  density: {
    title: "Local density percentile",
    what: "How crowded the sample's neighbourhood is compared with the rest of the dataset (0% = most isolated).",
    how: "Mean cosine similarity to the 5 nearest neighbours, converted to a percentile.",
    why: "Isolated samples are either rare-but-valuable or out-of-distribution. Isolation alone is not evidence of error.",
    action: "Isolated + model-uncertain + good quality usually means 'keep, it is rare'.",
  },
  reliability: {
    title: "Witness reliability",
    what: "How well a witness (model, neighbours, centroids) predicts the given labels on this particular dataset.",
    how: "Chance-corrected balanced accuracy: (balanced accuracy − 1/C) / (1 − 1/C), measured on training data.",
    why: "Weak witnesses should not drive verdicts. DataCourt automatically discounts them and says so.",
    action: "If all witnesses are weak, a stronger embedding backend (e.g. DINOv2) will give better evidence.",
  },
  self_influence: {
    title: "Self-influence (TracIn)",
    what: "How much a training sample's own gradient dominated training — high values mark memorised outliers or label errors.",
    how: "Σ over SGD checkpoints of learning rate × ‖∇loss(sample)‖² for the linear baseline head. Exact for the head, an approximation for the full system.",
    why: "Samples the model must memorise are disproportionately likely to be mislabelled.",
    action: "Use together with label evidence; do not remove on influence alone.",
  },
  harmful_influence: {
    title: "Harmful influence on failures",
    what: "Estimated amount by which training on this sample increased the loss of misclassified evaluation samples.",
    how: "Sum of negative TracIn scores between this training sample and each evaluation failure.",
    why: "Links model errors back to specific training data.",
    action: "Open the Blame Map for the affected failures, then test a change in the What-if Lab.",
  },
  cramers_v: {
    title: "Cramér's V (bias-corrected)",
    what: "Association strength (0–1) between a non-content cue — e.g. background colour — and the class label.",
    how: "Chi-square contingency statistic with Bergsma's small-sample correction, on the training split.",
    why: "If a label can be predicted from the background, a model can learn the background instead of the object.",
    action: "≥ 0.3 moderate, ≥ 0.5 strong. Diversify capture conditions and test the model with the cue removed.",
  },
  cue_only_accuracy: {
    title: "Cue-only accuracy",
    what: "Balanced accuracy of a classifier that sees only non-content cues (background, format, resolution…), never the object.",
    how: "Cross-validated logistic regression on one-hot encoded cues.",
    why: "Well above chance means the label is partly predictable without looking at the object.",
    action: "Compare with chance (1/number of classes).",
  },
  ece: {
    title: "Expected calibration error",
    what: "Average gap between the model's confidence and its accuracy.",
    how: "15 confidence bins; weighted |accuracy − mean confidence|. Probabilities are temperature-scaled on out-of-fold predictions.",
    why: "Tells you how literally to read model probabilities in the evidence.",
    action: "Above ~0.12 DataCourt marks model evidence as poorly calibrated and raises uncertainty.",
  },
  macro_f1: {
    title: "Macro F1",
    what: "Mean F1 score across classes, so small classes count as much as large ones.",
    how: "Unweighted mean of per-class F1 on the evaluation set.",
    why: "Accuracy hides failures on minority classes.",
    action: "Compare before/after on the preserved holdout in the What-if Lab.",
  },
  preserved_holdout: {
    title: "Preserved holdout",
    what: "Evaluation samples untouched by any proposed change and not involved in leakage.",
    how: "Evaluation split minus relabelled, removed and leaked samples.",
    why: "The fairest before/after comparison: the yardstick itself does not move.",
    action: "Trust improvements that hold here and exceed training-bootstrap noise.",
  },
  debt: {
    title: "Dataset Debt",
    what: "Accumulated, measurable data problems that make a dataset riskier to train on — in eight dimensions.",
    how: "Each dimension has a written formula over audited facts (shown on the Debt page) mapped to LOW / MODERATE / HIGH / CRITICAL with fixed thresholds.",
    why: "Turns scattered findings into a trackable number per dimension, across versions.",
    action: "Pay down the highest dimension first; watch the trend after each export.",
  },
  preflight: {
    title: "Preflight gate",
    what: "A rule-based READY / READY WITH WARNINGS / BLOCKED decision before training.",
    how: "Versioned rules (e.g. no exact duplicates across train/evaluation, every evaluated class has training data).",
    why: "Stops known-bad datasets from silently reaching training.",
    action: "Fix blocking checks, or have an admin record an override with a reason (logged in the ledger).",
  },
  ledger: {
    title: "Evidence ledger",
    what: "An append-only record of audits, verdicts, human decisions, overrides, experiments and exports.",
    how: "Each entry stores the SHA-256 of its payload and of the previous entry, forming a hash chain per workspace.",
    why: "Anyone can re-verify that the decision history was not edited after the fact.",
    action: "Run “Verify chain”; a break points to the first entry whose hash no longer matches.",
  },
  dna: {
    title: "Dataset DNA",
    what: "A versioned descriptive fingerprint: class mix, lighting, resolution, backgrounds, embedding geometry and issue profile.",
    how: "Histograms and centroids per version; drift uses Jensen–Shannon divergence and centroid shifts.",
    why: "Detects unexpected changes between versions (new camera, new background, ingestion mistakes).",
    action: "Investigate strong drift signals before retraining. DNA is not a cryptographic identity — use the manifest SHA-256 for that.",
  },
  verdict: {
    title: "Jury verdict",
    what: "The deterministic outcome of the case: KEEP, REVIEW, STRONG REVIEW, POSSIBLE RELABEL, POSSIBLE REMOVE, LIKELY RARE, LEAKAGE ACTION NEEDED or UNCERTAIN.",
    how: "Ordered, versioned rules over reason codes derived from measured evidence (see the rule trace on each case). No LLM is involved.",
    why: "Reproducible and auditable: the same evidence and configuration always give the same verdict.",
    action: "A verdict is a recommendation. The human decision is final.",
  },
  uncertainty: {
    title: "Uncertainty",
    what: "How much the evidence disagrees with itself or is incomplete.",
    how: "High when prosecution and defense carry similar weight; medium for rare/uncertain verdicts, poorly calibrated models or missing witnesses; low for deterministic evidence like identical files.",
    why: "High-uncertainty cases are where human judgement adds the most value.",
    action: "Read both sides before deciding.",
  },
  budget_coverage: {
    title: "Expected issue coverage",
    what: "Share of total case value (evidence risk × impact) included in the selected review queue.",
    how: "Greedy selection with diminishing returns per duplicate family and class, under an item or minute budget.",
    why: "Shows how much of the problem a limited review session can address.",
    action: "It ranks review effort; it does not promise a model improvement.",
  },
  leakage_risk: {
    title: "Leakage risk",
    what: "Likelihood that evaluation is inflated because near-identical data appears in training and evaluation.",
    how: "CRITICAL: byte-identical across train and test. HIGH: identical across train/val, or transformed copies touching test. MEDIUM: near duplicates. LOW: similar subjects without duplicate evidence.",
    why: "Leaked evaluation samples measure memorisation, not generalisation.",
    action: "Remove or move the evaluation copies; consider grouping splits by subject.",
  },
  quality: {
    title: "Potential quality issue",
    what: "A measured image property outside normal ranges (blur, exposure, contrast, resolution, information content, encoding).",
    how: "Absolute thresholds AND dataset-relative robust z-scores must agree; thresholds and rule version are stored with every finding.",
    why: "Unusable images add noise, but unusual images are not automatically unusable.",
    action: "Confirm visually before excluding. Deterministic checks (e.g. extension mismatch) are marked as such.",
  },
};
